DROP DATABASE IF EXISTS zoo;

CREATE DATABASE IF NOT EXISTS zoo CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

USE zoo;

CREATE TABLE chats (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    nom VARCHAR(255) NOT NULL, 
    yeux VARCHAR (255) NOT NULL,
    age INT NOT NULL 
)
ENGINE=InnoDB;